{{- if .Values.onvif.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.onvif.name }}
spec:
  protocol:
    name: onvif
    discoveryDetails:
      protocolHandler: |+
        onvif:
          ipAddresses: 
            action: {{ .Values.onvif.ipAddresses.action }}
            {{- if .Values.onvif.ipAddresses.items}}
            items:
            {{- toYaml .Values.onvif.ipAddresses.items | nindent 12 }}
            {{- else }}
            items: []
            {{- end }}
          macAddresses:
            action: {{ .Values.onvif.macAddresses.action }}
            {{- if .Values.onvif.macAddresses.items}}
            items:
            {{- toYaml .Values.onvif.macAddresses.items | nindent 12 }}
            {{- else }}
            items: []
            {{- end }}
          scopes:
            action: {{ .Values.onvif.scopes.action }}
            {{- if .Values.onvif.scopes.items}}
            items:
            {{- toYaml .Values.onvif.scopes.items | nindent 12 }}
            {{- else }}
            items: []
            {{- end }}
          discoveryTimeoutSeconds: {{ .Values.onvif.discoveryTimeoutSeconds }}
  {{- if .Values.onvif.brokerPod.image.repository }}
  {{- /* Only add broker pod spec if a broker image is provided */}}
  brokerPodSpec:
    containers:
    - name: {{ .Values.onvif.name }}-broker
      image: {{ .Values.onvif.brokerPod.image.repository | quote }}
      {{- with .Values.onvif.brokerPod.image.pullPolicy }}
      imagePullPolicy: {{ . }}
      {{- end }}
      {{- if .Values.onvif.brokerPod.env }}
      env:
        {{- range $key, $val := .Values.onvif.brokerPod.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
      {{- end }}
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- /* Only add service specs if a broker image was specified and service creation was not disabled */}}
  {{- if .Values.onvif.brokerPod.image.repository }}
  {{- if .Values.onvif.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.onvif.instanceService.type }}
    ports:
    - name: {{ .Values.onvif.instanceService.portName }}
      port: {{ .Values.onvif.instanceService.port }}
      protocol: {{ .Values.onvif.instanceService.protocol }}
      targetPort: {{ .Values.onvif.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.onvif.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.onvif.configurationService.type }}
    ports:
    - name: {{ .Values.onvif.configurationService.portName }}
      port: {{ .Values.onvif.configurationService.port }}
      protocol: {{ .Values.onvif.configurationService.protocol }}
      targetPort: {{ .Values.onvif.configurationService.targetPort }}
  {{- end }}
  {{- end }}
  {{- if .Values.onvif.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  {{- end }}
  capacity: {{ .Values.onvif.capacity }}
{{- end }}
---
{{- if .Values.agent.slim}}
{{- if .Values.onvif.discovery.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akri-onvif-discovery-daemonset
spec:
  selector:
    matchLabels:
      name: akri-onvif-discovery
  template:
    metadata:
      labels:
        name: akri-onvif-discovery
    spec:
      containers:
      - name: akri-onvif-discovery
        {{- if .Values.useDevelopmentContainers }}
        {{- if .Values.useLatestContainers }}
        image: {{ printf "%s:latest-dev" .Values.onvif.discovery.image.repository | quote }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.onvif.discovery.image.repository (default (printf "v%s-dev" .Chart.AppVersion) .Values.onvif.discovery.image.tag) | quote }}
        {{- end }}
        {{- else }}
        {{- if .Values.useLatestContainers }}
        image: {{ printf "%s:latest" .Values.onvif.discovery.image.repository | quote }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.onvif.discovery.image.repository (default (printf "v%s" .Chart.AppVersion) .Values.onvif.discovery.image.tag) | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.onvif.discovery.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end}}
        {{- if .Values.onvif.discovery.useNetworkConnection }}
        ports:
        - name: discovery
          containerPort: {{ .Values.onvif.discovery.port }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- end }}
        volumeMounts:
        - name: agent-registration
          mountPath: /var/lib/akri
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.onvif.discovery.nodeSelectors }}
      nodeSelector:
      {{- toYaml .Values.onvif.discovery.nodeSelectors | nindent 8 }}
      {{- end }}
      volumes:
      - name: agent-registration
        hostPath:
          path: /var/lib/akri
{{- end }}
{{- end }}