{{- if .Values.onvif.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.onvif.name }}
spec:
  discoveryHandler:
    name: onvif
    discoveryDetails: |+
      ipAddresses: 
        action: {{ .Values.onvif.ipAddresses.action }}
        {{- if .Values.onvif.ipAddresses.items}}
        items:
        {{- toYaml .Values.onvif.ipAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      macAddresses:
        action: {{ .Values.onvif.macAddresses.action }}
        {{- if .Values.onvif.macAddresses.items}}
        items:
        {{- toYaml .Values.onvif.macAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      scopes:
        action: {{ .Values.onvif.scopes.action }}
        {{- if .Values.onvif.scopes.items}}
        items:
        {{- toYaml .Values.onvif.scopes.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      discoveryTimeoutSeconds: {{ .Values.onvif.discoveryTimeoutSeconds }}
  {{- if .Values.onvif.brokerPod.image.repository }}
  {{- /* Only add broker pod spec if a broker image is provided */}}
  brokerPodSpec:
    containers:
    - name: {{ .Values.onvif.name }}-broker
      image: {{ printf "%s:%s" .Values.onvif.brokerPod.image.repository .Values.onvif.brokerPod.image.tag | quote }}
      {{- with .Values.onvif.brokerPod.image.pullPolicy }}
      imagePullPolicy: {{ . }}
      {{- end }}
      {{- if .Values.onvif.brokerPod.env }}
      env:
        {{- range $key, $val := .Values.onvif.brokerPod.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
      {{- end }}
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- /* Only add service specs if a broker image was specified and service creation was not disabled */}}
  {{- if .Values.onvif.brokerPod.image.repository }}
  {{- if .Values.onvif.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.onvif.instanceService.type }}
    ports:
    - name: {{ .Values.onvif.instanceService.portName }}
      port: {{ .Values.onvif.instanceService.port }}
      protocol: {{ .Values.onvif.instanceService.protocol }}
      targetPort: {{ .Values.onvif.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.onvif.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.onvif.configurationService.type }}
    ports:
    - name: {{ .Values.onvif.configurationService.portName }}
      port: {{ .Values.onvif.configurationService.port }}
      protocol: {{ .Values.onvif.configurationService.protocol }}
      targetPort: {{ .Values.onvif.configurationService.targetPort }}
  {{- end }}
  {{- end }}
  {{- if .Values.onvif.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  {{- end }}
  capacity: {{ .Values.onvif.capacity }}
{{- end }}