{{- if .Values.onvif.configuration.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.onvif.configuration.name }}
spec:
  discoveryHandler:
    name: onvif
    discoveryDetails: |+
      ipAddresses: 
        action: {{ .Values.onvif.configuration.discoveryDetails.ipAddresses.action }}
        {{- if .Values.onvif.configuration.discoveryDetails.ipAddresses.items}}
        items:
        {{- toYaml .Values.onvif.configuration.discoveryDetails.ipAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      macAddresses:
        action: {{ .Values.onvif.configuration.discoveryDetails.macAddresses.action }}
        {{- if .Values.onvif.configuration.discoveryDetails.macAddresses.items}}
        items:
        {{- toYaml .Values.onvif.configuration.discoveryDetails.macAddresses.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      scopes:
        action: {{ .Values.onvif.configuration.discoveryDetails.scopes.action }}
        {{- if .Values.onvif.configuration.discoveryDetails.scopes.items}}
        items:
        {{- toYaml .Values.onvif.configuration.discoveryDetails.scopes.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}
      discoveryTimeoutSeconds: {{ .Values.onvif.configuration.discoveryDetails.discoveryTimeoutSeconds }}
  {{- if or .Values.onvif.configuration.brokerPod.image.repository .Values.onvif.configuration.brokerJob.image.repository }}
  brokerSpec:
    {{- if .Values.onvif.configuration.brokerPod.image.repository }}
    {{- /* Only add broker pod spec if a broker image is provided */}}
    brokerPodSpec:
      containers:
      - name: {{ .Values.onvif.configuration.name }}-broker
        image: {{ printf "%s:%s" .Values.onvif.configuration.brokerPod.image.repository .Values.onvif.configuration.brokerPod.image.tag | quote }}
        {{- with .Values.onvif.configuration.brokerPod.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        {{- if .Values.onvif.configuration.brokerPod.env }}
        env:
          {{- range $key, $val := .Values.onvif.configuration.brokerPod.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            {{`"{{PLACEHOLDER}}"`}} : "1"
            memory: {{ .Values.onvif.configuration.brokerPod.resources.memoryRequest }}
            cpu: {{ .Values.onvif.configuration.brokerPod.resources.cpuRequest }}
          limits:
            {{`"{{PLACEHOLDER}}"`}} : "1"
            memory: {{ .Values.onvif.configuration.brokerPod.resources.memoryLimit }}
            cpu: {{ .Values.onvif.configuration.brokerPod.resources.cpuLimit }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- else }}
    brokerJobSpec:
      template:
        {{- if .Values.onvif.configuration.brokerJob.enablePodAntiAffinity }}
        metadata:
          labels:
            app: {{ .Values.onvif.configuration.name }}-broker
        {{- end }}
        spec:
          containers:
          - name: {{ .Values.onvif.configuration.name }}-broker
            image: {{ printf "%s:%s" .Values.onvif.configuration.brokerJob.image.repository .Values.onvif.configuration.brokerPod.image.tag | quote }}
            {{- if .Values.onvif.configuration.brokerJob.command }}
            command: 
              {{- toYaml .Values.onvif.configuration.brokerJob.command | nindent 14 }}
            {{- end }}
            {{- with .Values.onvif.configuration.pullPolicy }}
            imagePullPolicy: {{ . }}
            {{- end }}
            resources:
              requests:
                {{`"{{PLACEHOLDER}}"`}} : "1"
                memory: {{ .Values.onvif.configuration.brokerJob.resources.memoryRequest }}
                cpu: {{ .Values.onvif.configuration.brokerJob.resources.cpuRequest }}
              limits:
                {{`"{{PLACEHOLDER}}"`}} : "1"
                memory: {{ .Values.onvif.configuration.brokerJob.resources.memoryLimit }}
                cpu: {{ .Values.onvif.configuration.brokerJob.resources.cpuLimit }}
          restartPolicy: {{ .Values.onvif.configuration.brokerJob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 6 }}
          {{- end }}
          {{- if .Values.onvif.configuration.brokerJob.enablePodAntiAffinity }}
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Values.onvif.configuration.name }}-broker
                topologyKey: "kubernetes.io/hostname"
          {{- end }}
      backoffLimit: {{ .Values.onvif.configuration.brokerJob.backoffLimit }}
      parallelism: {{ .Values.onvif.configuration.brokerJob.parallelism }}
      completions: {{ .Values.onvif.configuration.brokerJob.completions }}
    {{- end }}
  {{- end }}
  {{- /* Only add service specs if a broker image was specified and service creation was not disabled */}}
  {{- if .Values.onvif.configuration.brokerPod.image.repository }}
  {{- if .Values.onvif.configuration.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.onvif.configuration.instanceService.type }}
    ports:
    - name: {{ .Values.onvif.configuration.instanceService.portName }}
      port: {{ .Values.onvif.configuration.instanceService.port }}
      protocol: {{ .Values.onvif.configuration.instanceService.protocol }}
      targetPort: {{ .Values.onvif.configuration.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.onvif.configuration.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.onvif.configuration.configurationService.type }}
    ports:
    - name: {{ .Values.onvif.configuration.configurationService.portName }}
      port: {{ .Values.onvif.configuration.configurationService.port }}
      protocol: {{ .Values.onvif.configuration.configurationService.protocol }}
      targetPort: {{ .Values.onvif.configuration.configurationService.targetPort }}
  {{- end }}
  {{- end }}
  {{- if .Values.onvif.configuration.brokerProperties }}
  brokerProperties:
  {{- range $key, $val := .Values.onvif.configuration.brokerProperties }}
  {{- $key | nindent 4 }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  brokerProperties: {}
  {{- end }}
  capacity: {{ .Values.onvif.configuration.capacity }}
{{- end }}