{{- if .Values.opcua.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.opcua.name }}
spec:
  protocol:
    name: opcua
    discoveryDetails:
      protocolHandler: |+
        opcua:
          opcuaDiscoveryMethod: 
            standard:
              discoveryUrls: 
              {{- toYaml .Values.opcua.discoveryUrls | nindent 14 }}
          applicationNames:
            action: {{ .Values.opcua.applicationNames.action }}
            {{- if .Values.opcua.applicationNames.items}}
            items:
            {{- toYaml .Values.opcua.applicationNames.items | nindent 12 }}
            {{- else }}
            items: []
            {{- end }}
  {{- if .Values.opcua.brokerPod.image.repository }}
  {{- /* Only add broker pod spec if a broker image is provided */}}
  brokerPodSpec:
    containers:
    - name: {{ .Values.opcua.name }}-broker
      image: {{ .Values.opcua.brokerPod.image.repository | quote }}
      {{- with .Values.opcua.brokerPod.image.pullPolicy }}
      imagePullPolicy: {{ . }}
      {{- end }}
      {{- if .Values.opcua.brokerPod.env }}
      env:
        {{- range $key, $val := .Values.opcua.brokerPod.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
      {{- end }}
      resources:
        limits:
          {{`"{{PLACEHOLDER}}"`}} : "1"
      {{- if .Values.opcua.mountCertificates}}
      volumeMounts:
      - name: credentials
        mountPath: "/etc/opcua-certs/client-pki"
        readOnly: false
      {{- end }}
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.opcua.mountCertificates }}
    volumes:
    - name: credentials
      secret:
        secretName: opcua-broker-credentials
        items:
        - key: client_certificate
          path: own/certs/AkriBroker.der
        - key: client_key
          path: own/private/AkriBroker.pfx
        - key: ca_certificate
          path: trusted/certs/SomeCA.der
        - key: ca_crl
          path: trusted/crl/SomeCA.crl
    {{- end }}
  {{- end }}
  {{- /* Only add service specs if a broker image was specified and service
  creation was not disabled */}}
  {{- if .Values.opcua.brokerPod.image.repository }}
  {{- if .Values.opcua.createInstanceServices }}
  instanceServiceSpec:
    type: {{ .Values.opcua.instanceService.type }}
    ports:
    - name: grpc
      port: {{ .Values.opcua.instanceService.port }}
      protocol: {{ .Values.opcua.instanceService.protocol }}
      targetPort: {{ .Values.opcua.instanceService.targetPort }}
  {{- end }}
  {{- if .Values.opcua.createConfigurationService }}
  configurationServiceSpec:
    type: {{ .Values.opcua.configurationService.type }}
    ports:
    - name: grpc
      port: {{ .Values.opcua.configurationService.port }}
      protocol: {{ .Values.opcua.configurationService.protocol }}
      targetPort: {{ .Values.opcua.configurationService.targetPort }}
  {{- end }}
  {{- end }}
  {{- if .Values.opcua.properties }}
  properties:
  {{- toYaml . | nindent 4 }}
  {{- else }}
  properties: {}
  {{- end }}
  capacity: {{ .Values.opcua.capacity }}
{{- end }}
---
{{- if .Values.agent.slim}}
{{- if .Values.opcua.discovery.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akri-opcua-discovery-daemonset
spec:
  selector:
    matchLabels:
      name: akri-opcua-discovery
  template:
    metadata:
      labels:
        name: akri-opcua-discovery
    spec:
      containers:
      - name: akri-opcua-discovery
        {{- if .Values.useDevelopmentContainers }}
        {{- if .Values.useLatestContainers }}
        image: {{ printf "%s:latest-dev" .Values.opcua.discovery.image.repository | quote }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.opcua.discovery.image.repository (default (printf "v%s-dev" .Chart.AppVersion) .Values.opcua.discovery.image.tag) | quote }}
        {{- end }}
        {{- else }}
        {{- if .Values.useLatestContainers }}
        image: {{ printf "%s:latest" .Values.opcua.discovery.image.repository | quote }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.opcua.discovery.image.repository (default (printf "v%s" .Chart.AppVersion) .Values.opcua.discovery.image.tag) | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.opcua.discovery.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end}}
        {{- if .Values.opcua.discovery.useNetworkConnection }}
        ports:
        - name: discovery
          containerPort: {{ .Values.opcua.discovery.port }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- end }}
        volumeMounts:
        - name: agent-registration
          mountPath: /var/lib/akri
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.opcua.discovery.nodeSelectors }}
      nodeSelector:
      {{- toYaml .Values.opcua.discovery.nodeSelectors | nindent 8 }}
      {{- end }}
      volumes:
      - name: agent-registration
        hostPath:
          path: /var/lib/akri
{{- end }}
{{- end }}