[package]
name = "udev-video-broker"
version = "0.3.1"
authors = ["Kate Goldenring <kate.goldenring@microsoft.com>", "<bfjelds@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akri-shared = { path = "../../../shared" }
env_logger = "0.6.1"
futures = { version = "0.1", package = "futures" }
lazy_static = "1.4"
log = "0.4.3"
prometheus = { version = "0.11.0", features = ["process"] }
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
tonic = "0.1"
rscam = "0.5.5"

[build-dependencies]
tonic-build = "0.1.1"