name: Build Webhook Configuration

on:
  workflow_run:
    workflows: ["Build Production Rust Code"]
    types: 
      - completed

env:
  AKRI_COMPONENT: webhook-configuration
  MAKEFILE_COMPONENT: webhook-configuration

jobs:
  per-arch:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        arch:
          - arm64v8
          - arm32v7
          - amd64

    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare To Install
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Deps
        run: |
          yarn install
          yarn add @actions/core @actions/github @actions/exec fs

      - name: Download rust build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          commit: ${{ github.event.workflow_run.head_sha }}
          name: rust-${{ matrix.arch.label }}-binaries
          path: /tmp

      - name: Unpack Rust binaries
        run: |
          tar -xvf /tmp/rust-${{ matrix.arch.label }}-binaries.tar

      - name: Run Per-Arch component build for ${{ env.AKRI_COMPONENT }}
        uses: ./.github/actions/build-component-per-arch
        with:
          github_event_name: ${{ github.event.workflow_run.event }}
          github_ref: ${{ github.ref }}
          container_name: ${{ env.AKRI_COMPONENT }}
          container_prefix: ghcr.io/deislabs/akri
          container_registry_base_url: ghcr.io
          container_registry_username: ${{ secrets.crUsername }}
          container_registry_password: ${{ secrets.crPassword }}
          makefile_component_name: ${{ env.MAKEFILE_COMPONENT }}
          platform: ${{ matrix.arch }}
          build_rust: "0"

  multi-arch:
    if: (github.event.workflow_run.event == 'release') || (github.event.workflow_run.event == 'push' && github.ref == 'refs/heads/main')
    needs: per-arch
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare To Install
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Deps
        run: |
          yarn install
          yarn add @actions/core @actions/github @actions/exec fs

      - name: Run Multi-Arch component build for ${{ env.AKRI_COMPONENT }}
        uses: ./.github/actions/build-component-multi-arch
        with:
          github_event_name: ${{ github.event.workflow_run.event }}
          container_name: ${{ env.AKRI_COMPONENT }}
          container_prefix: ghcr.io/deislabs/akri
          container_registry_base_url: ghcr.io
          container_registry_username: ${{ secrets.crUsername }}
          container_registry_password: ${{ secrets.crPassword }}
          makefile_component_name: ${{ env.MAKEFILE_COMPONENT }}
