name: Check versioning

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '**.md'
      - Notice.txt
      - '.github/workflows/check-versioning.yml'
      - '.github/workflows/check-rust.yml'
      - '.github/workflows/run-tarpaulin.yml'
      - '.github/workflows/run-test-cases.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODEOWNERS'
      - '.vscode/**'
      - docs/**
      - scripts/**
      - tests/**
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '**.md'
      - Notice.txt
      - '.github/workflows/check-versioning.yml'
      - '.github/workflows/check-rust.yml'
      - '.github/workflows/run-tarpaulin.yml'
      - '.github/workflows/run-test-cases.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODEOWNERS'
      - '.vscode/**'
      - docs/**
      - scripts/**
      - tests/**
  release:
    types:
      - published
  issues:
    types:
      - labeled

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # Only run version check for PRs. If PR does NOT have "same version" label, then ensure that
    # version.txt is different from what is in main.
    - if: startsWith(github.event_name, 'pull_request') && !contains(github.event.pull_request.labels.*.name, 'same version')
      name: Run version check (triggered by "same version" label)
      run: ./version.sh -c
    # If PR does have "same version" label, then do not check that version.txt is different from
    # what is in main.
    - if: startsWith(github.event_name, 'pull_request') && contains(github.event.pull_request.labels.*.name, 'same version')
      name: Run version check (skip, triggered by "same version" label)
      run: ./version.sh -c -s
